import.meta;

export default function getFirebaseConfig() {
	return {
		apiKey: __SNOWPACK_ENV__.SNOWPACK_PUBLIC_FIREBASE_API_KEY,
		authDomain: __SNOWPACK_ENV__.SNOWPACK_PUBLIC_FIREBASE_AUTH_DOMAIN,
		databaseURL: __SNOWPACK_ENV__.SNOWPACK_PUBLIC_FIREBASE_DATABASE_URL,
		projectId: __SNOWPACK_ENV__.SNOWPACK_PUBLIC_FIREBASE_PROJECT_ID,
		storageBucket: __SNOWPACK_ENV__.SNOWPACK_PUBLIC_FIREBASE_STORAGE_BUCKET,
		messagingSenderId:
			__SNOWPACK_ENV__.SNOWPACK_PUBLIC_FIREBASE_MESSAGE_SENDER_ID,
		appId: __SNOWPACK_ENV__.SNOWPACK_PUBLIC_FIREBASE_APP_ID,
	};
}
